---
- name: Create config directory
  ansible.builtin.file:
    path: /opt/app-archisteamfarm/config
    state: directory
    owner: '1000'
    group: '1000'
    mode: 0755

- name: Create plugins directory
  ansible.builtin.file:
    path: /opt/app-archisteamfarm/plugins
    state: directory
    owner: '1000'
    group: '1000'
    mode: 0755

- name: Ensure justarchi/archisteamfarm image is pulled
  community.docker.docker_image:
    name: docker.io/justarchi/archisteamfarm
    source: pull
    force_source: yes
  register: pulled

- name: Remove archisteamfarm container
  community.docker.docker_container:
    name: archisteamfarm
    state: absent
  when: pulled.changed

- name: Get infos on archisteamfarm container
  community.docker.docker_container_info:
    name: archisteamfarm
  register: result

- name: Create archisteamfarm container
  ansible.builtin.shell: |
    docker run -d \
    --name=archisteamfarm \
    -v /opt/app-archisteamfarm/config:/app/config:Z \
    -v /opt/app-archisteamfarm/plugins:/app/plugins:Z \
    --network=app-network \
    --restart unless-stopped \
    docker.io/justarchi/archisteamfarm
  when:
    pulled.changed
    or
    result.exists == false
