---
- name: Create app network
  community.docker.docker_network:
    name: app-network

- name: Create directorys
  ansible.builtin.file:
    path: /opt/docker-redis/data
    state: directory
    owner: '1001'
    group: '1001'
    mode: 0755

- name: Ensure bitnami/redis image is pulled
  community.docker.docker_image:
    name: docker.io/bitnami/redis
    source: pull
    force_source: yes
  register: pulled

- name: Remove redis container
  community.docker.docker_container:
    name: redis
    state: absent
  when: pulled.changed

- name: Get infos on redis container
  community.docker.docker_container_info:
    name: redis
  register: result

- name: Create postgresql container
  ansible.builtin.shell: |
    docker run -d \
    --name=redis \
    -e ALLOW_EMPTY_PASSWORD={{docker_redis_allow_empty_password}} \
    -e REDIS_DISABLE_COMMANDS={{docker_redis_redis_disable_commands}} \
    -e REDIS_PASSWORD={{docker_redis_redis_password}} \
    -e REDIS_ACLFILE={{docker_redis_redis_aclfile}} \
    -v /opt/docker-redis/data:/bitnami/redis/data:Z \
    --network=app-network \
    --restart unless-stopped \
    docker.io/bitnami/redis
  when:
    pulled.changed
    or
    result.exists == false
