---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_foldingathome_dir}}/config"
    state: directory
    owner: "{{app_foldingathome_puid}}"
    group: "{{app_foldingathome_pgid}}"
    mode: 0755

- name: Ensure linuxserver/foldingathome image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/foldingathome
    source: pull
    force_source: yes
  register: pulled

- name: Remove foldingathome container
  community.docker.docker_container:
    name: foldingathome
    state: absent
  when: pulled.changed

- name: Get infos on foldingathome container
  community.docker.docker_container_info:
    name: foldingathome
  register: result

- name: Create foldingathome container
  ansible.builtin.shell: |
    docker run -d \
    --name=foldingathome \
    -e PUID={{app_foldingathome_puid}} \
    -e PGID={{app_foldingathome_pgid}} \
    -e TZ={{app_foldingathome_tz}} \
    -v /{{app_foldingathome_dir}}/config:/config:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/foldingathome
  when: 
    pulled.changed
    or
    result.exists == false
