---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_calibre_dir}}/config"
    state: directory
    owner: "{{app_calibre_puid}}"
    group: "{{app_calibre_pgid}}"
    mode: 0755

- name: Ensure linuxserver/calibre image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/calibre
    source: pull
    force_source: yes
  register: pulled

- name: Remove calibre container
  community.docker.docker_container:
    name: calibre
    state: absent
  when: pulled.changed

- name: Get infos on calibre container
  community.docker.docker_container_info:
    name: calibre
  register: result

- name: Create calibre container
  ansible.builtin.shell: |
    docker run -d \
    --name=calibre \
    -e PUID={{app_calibre_puid}} \
    -e PGID={{app_calibre_pgid}} \
    -e TZ={{app_calibre_tz}} \
    -e PASSWORD={{app_calibre_password}} \
    -e CLI_ARGS={{app_calibre_cli_args}} \
    -v /{{app_calibre_dir}}/config:/config:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/calibre
  when: 
    pulled.changed
    or
    result.exists == false
