---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_emby_dir}}/config"
    state: directory
    owner: "{{app_emby_puid}}"
    group: "{{app_emby_pgid}}"
    mode: 0755

- name: Create tvshows directory
  ansible.builtin.file:
    path: "{{app_emby_dir}}/tvshows"
    state: directory
    owner: "{{app_emby_puid}}"
    group: "{{app_emby_pgid}}"
    mode: 0755

- name: Create movies directory
  ansible.builtin.file:
    path: "{{app_emby_dir}}/movies"
    state: directory
    owner: "{{app_emby_puid}}"
    group: "{{app_emby_pgid}}"
    mode: 0755

- name: Ensure linuxserver/emby image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/emby
    source: pull
    force_source: yes
  register: pulled

- name: Remove emby container
  community.docker.docker_container:
    name: emby
    state: absent
  when: pulled.changed

- name: Get infos on emby container
  community.docker.docker_container_info:
    name: emby
  register: result

- name: Create emby container
  ansible.builtin.shell: |
    docker run -d \
    --name=emby \
    -e PUID={{app_emby_puid}} \
    -e PGID={{app_emby_pgid}} \
    -e TZ={{app_emby_tz}} \
    -v /{{app_emby_dir}}/config:/config:Z \
    -v /{{app_emby_dir}}/tvshows:/data/tvshows:Z \
    -v /{{app_emby_dir}}/movies:/data/movies:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/emby
  when: 
    pulled.changed
    or
    result.exists == false
