---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_mstream_dir}}/config"
    state: directory
    owner: "{{app_mstream_puid}}"
    group: "{{app_mstream_pgid}}"
    mode: 0755

- name: Create music directory
  ansible.builtin.file:
    path: "{{app_mstream_dir}}/music"
    state: directory
    owner: "{{app_mstream_puid}}"
    group: "{{app_mstream_pgid}}"
    mode: 0755

- name: Ensure linuxserver/mstream image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/mstream
    source: pull
    force_source: yes
  register: pulled

- name: Remove mstream container
  community.docker.docker_container:
    name: mstream
    state: absent
  when: pulled.changed

- name: Get infos on mstream container
  community.docker.docker_container_info:
    name: mstream
  register: result

- name: Create mstream container
  ansible.builtin.shell: |
    docker run -d \
    --name=mstream \
    -e PUID={{app_mstream_puid}} \
    -e PGID={{app_mstream_pgid}} \
    -e TZ={{app_mstream_tz}} \
    -v /{{app_mstream_dir}}/config:/config:Z \
    -v /{{app_mstream_dir}}/tvshows:/music:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/mstream
  when: 
    pulled.changed
    or
    result.exists == false
