---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_lidarr_dir}}/config"
    state: directory
    owner: "{{app_lidarr_puid}}"
    group: "{{app_lidarr_pgid}}"
    mode: 0755

- name: Create music directory
  ansible.builtin.file:
    path: "{{app_lidarr_dir}}/music"
    state: directory
    owner: "{{app_lidarr_puid}}"
    group: "{{app_lidarr_pgid}}"
    mode: 0755

- name: Create downloads directory
  ansible.builtin.file:
    path: "{{app_lidarr_dir}}/downloads"
    state: directory
    owner: "{{app_lidarr_puid}}"
    group: "{{app_lidarr_pgid}}"
    mode: 0755

- name: Ensure linuxserver/lidarr image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/lidarr
    source: pull
    force_source: yes
  register: pulled

- name: Remove lidarr container
  community.docker.docker_container:
    name: lidarr
    state: absent
  when: pulled.changed

- name: Get infos on lidarr container
  community.docker.docker_container_info:
    name: lidarr
  register: result

- name: Create lidarr container
  ansible.builtin.shell: |
    docker run -d \
    --name=lidarr \
    -e PUID={{app_lidarr_puid}} \
    -e PGID={{app_lidarr_pgid}} \
    -e TZ={{app_lidarr_tz}} \
    -v /{{app_lidarr_dir}}/config:/config:Z \
    -v /{{app_lidarr_dir}}/music:/music:Z \
    -v /{{app_lidarr_dir}}/downloads:/downloads:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/lidarr
  when: 
    pulled.changed
    or
    result.exists == false
