---
- name: Create config directory
  ansible.builtin.file:
    path: /opt/app-nextcloud/config
    state: directory
    owner: "{{app_nextcloud_puid}}"
    group: "{{app_nextcloud_pgid}}"
    mode: 0755

- name: Create data directory
  ansible.builtin.file:
    path: /opt/app-nextcloud/data
    state: directory
    owner: "{{app_nextcloud_puid}}"
    group: "{{app_nextcloud_pgid}}"
    mode: 0755

- name: Ensure linuxserver/nextcloud image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/nextcloud
    source: pull
    force_source: yes
  register: pulled

- name: Remove nextcloud container
  community.docker.docker_container:
    name: nextcloud
    state: absent
  when: pulled.changed

- name: Get infos on nextcloud container
  community.docker.docker_container_info:
    name: nextcloud
  register: result

- name: Create nextcloud container
  ansible.builtin.shell: |
    docker run -d \
    --name=nextcloud \
    -e PUID={{app_nextcloud_puid}} \
    -e PGID={{app_nextcloud_pgid}} \
    -e TZ={{app_nextcloud_tz}} \
    -v /opt/app-nextcloud/config:/config:Z \
    -v /opt/app-nextcloud/data:/data:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/nextcloud
  when: 
    pulled.changed
    or
    result.exists == false
