---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_duplicati_dir}}/config"
    state: directory
    owner: "{{app_duplicati_puid}}"
    group: "{{app_duplicati_pgid}}"
    mode: 0755

- name: Create backups directory
  ansible.builtin.file:
    path: "{{app_duplicati_dir}}/backups"
    state: directory
    owner: "{{app_duplicati_puid}}"
    group: "{{app_duplicati_pgid}}"
    mode: 0755

- name: Create source directory
  ansible.builtin.file:
    path: "{{app_duplicati_dir}}/source"
    state: directory
    owner: "{{app_duplicati_puid}}"
    group: "{{app_duplicati_pgid}}"
    mode: 0755

- name: Ensure linuxserver/duplicati image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/duplicati
    source: pull
    force_source: yes
  register: pulled

- name: Remove duplicati container
  community.docker.docker_container:
    name: duplicati
    state: absent
  when: pulled.changed

- name: Get infos on duplicati container
  community.docker.docker_container_info:
    name: duplicati
  register: result

- name: Create duplicati container
  ansible.builtin.shell: |
    docker run -d \
    --name=duplicati \
    -e PUID={{app_duplicati_puid}} \
    -e PGID={{app_duplicati_pgid}} \
    -e TZ={{app_duplicati_tz}} \
    -e CLI_ARGS={{app_duplicati_cli_args}} \
    -v /{{app_duplicati_dir}}/config:/config:Z \
    -v /{{app_duplicati_dir}}/backups:/backups:Z \
    -v /{{app_duplicati_dir}}/source:/source:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/duplicati
  when: 
    pulled.changed
    or
    result.exists == false
