---
- name: Install Fail2ban
  package:
    name: "{{ system_fail2ban_package }}"
    state: "{{ system_fail2ban_package_state }}"
  notify: restart fail2ban
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create fail2ban jail file
  ansible.builtin.blockinfile:
    dest: /etc/fail2ban/jail.local
    create: true
    block: "{{ system_fail2ban_jail_local }}"

- name: Ensure Fail2ban is started and enabled at boot
  service:
    name: fail2ban
    state: "{{ system_fail2ban_service_state }}"
    enabled: "{{ system_fail2ban_service_enabled }}"
  ignore_errors: "{{ ansible_check_mode }}"
