---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_emulatorjs_dir}}/config"
    state: directory
    owner: "{{app_emulatorjs_puid}}"
    group: "{{app_emulatorjs_pgid}}"
    mode: 0755

- name: Create data directory
  ansible.builtin.file:
    path: "{{app_emulatorjs_dir}}/data"
    state: directory
    owner: "{{app_emulatorjs_puid}}"
    group: "{{app_emulatorjs_pgid}}"
    mode: 0755

- name: Ensure linuxserver/emulatorjs image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/emulatorjs
    source: pull
    force_source: yes
  register: pulled

- name: Remove emulatorjs container
  community.docker.docker_container:
    name: emulatorjs
    state: absent
  when: pulled.changed

- name: Get infos on emulatorjs container
  community.docker.docker_container_info:
    name: emulatorjs
  register: result

- name: Create emulatorjs container
  ansible.builtin.shell: |
    docker run -d \
    --name=emulatorjs \
    -e PUID={{app_emulatorjs_puid}} \
    -e PGID={{app_emulatorjs_pgid}} \
    -e TZ={{app_emulatorjs_tz}} \
    -v /{{app_emulatorjs_dir}}/config:/config:Z \
    -v /{{app_emulatorjs_dir}}/data:/data:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/emulatorjs
  when: 
    pulled.changed
    or
    result.exists == false
