---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_headphones_dir}}/config"
    state: directory
    owner: "{{app_headphones_puid}}"
    group: "{{app_headphones_pgid}}"
    mode: 0755

- name: Create downloads directory
  ansible.builtin.file:
    path: "{{app_headphones_dir}}/downloads"
    state: directory
    owner: "{{app_headphones_puid}}"
    group: "{{app_headphones_pgid}}"
    mode: 0755

- name: Create music directory
  ansible.builtin.file:
    path: "{{app_headphones_dir}}/music"
    state: directory
    owner: "{{app_headphones_puid}}"
    group: "{{app_headphones_pgid}}"
    mode: 0755

- name: Ensure linuxserver/headphones image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/headphones
    source: pull
    force_source: yes
  register: pulled

- name: Remove headphones container
  community.docker.docker_container:
    name: headphones
    state: absent
  when: pulled.changed

- name: Get infos on headphones container
  community.docker.docker_container_info:
    name: headphones
  register: result

- name: Create headphones container
  ansible.builtin.shell: |
    docker run -d \
    --name=headphones \
    -e PUID={{app_headphones_puid}} \
    -e PGID={{app_headphones_pgid}} \
    -e TZ={{app_headphones_tz}} \
    -v /{{app_headphones_dir}}/config:/config:Z \
    -v /{{app_headphones_dir}}/downloads:/downloads:Z \
    -v /{{app_headphones_dir}}/music:/music:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/headphones
  when: 
    pulled.changed
    or
    result.exists == false
