---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_deluge_dir}}/config"
    state: directory
    owner: "{{app_deluge_puid}}"
    group: "{{app_deluge_pgid}}"
    mode: 0755

- name: Create downloads directory
  ansible.builtin.file:
    path: "{{app_deluge_dir}}/downloads"
    state: directory
    owner: "{{app_deluge_puid}}"
    group: "{{app_deluge_pgid}}"
    mode: 0755

- name: Ensure linuxserver/deluge image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/deluge
    source: pull
    force_source: yes
  register: pulled

- name: Remove deluge container
  community.docker.docker_container:
    name: deluge
    state: absent
  when: pulled.changed

- name: Get infos on deluge container
  community.docker.docker_container_info:
    name: deluge
  register: result

- name: Create deluge container
  ansible.builtin.shell: |
    docker run -d \
    --name=deluge \
    -e PUID={{app_deluge_puid}} \
    -e PGID={{app_deluge_pgid}} \
    -e TZ={{app_deluge_tz}} \
    -e DELUGE_LOGLEVEL={{app_deluge_loglevel}} \
    -v /{{app_deluge_dir}}/config:/config:Z \
    -v /{{app_deluge_dir}}/downloads:/downloads:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/deluge
  when: 
    pulled.changed
    or
    result.exists == false
