---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_homeassistant_dir}}/config"
    state: directory
    owner: "{{app_homeassistant_puid}}"
    group: "{{app_homeassistant_pgid}}"
    mode: 0755

- name: Ensure linuxserver/homeassistant image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/homeassistant
    source: pull
    force_source: yes
  register: pulled

- name: Remove homeassistant container
  community.docker.docker_container:
    name: homeassistant
    state: absent
  when: pulled.changed

- name: Get infos on homeassistant container
  community.docker.docker_container_info:
    name: homeassistant
  register: result

- name: Create homeassistant container
  ansible.builtin.shell: |
    docker run -d \
    --name=homeassistant \
    -e PUID={{app_homeassistant_puid}} \
    -e PGID={{app_homeassistant_pgid}} \
    -e TZ={{app_homeassistant_tz}} \
    -v /{{app_homeassistant_dir}}/config:/config:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/homeassistant
  when: 
    pulled.changed
    or
    result.exists == false
