---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_medusa_dir}}/config"
    state: directory
    owner: "{{app_medusa_puid}}"
    group: "{{app_medusa_pgid}}"
    mode: 0755

- name: Create downloads directory
  ansible.builtin.file:
    path: "{{app_medusa_dir}}/downloads"
    state: directory
    owner: "{{app_medusa_puid}}"
    group: "{{app_medusa_pgid}}"
    mode: 0755

- name: Create tv directory
  ansible.builtin.file:
    path: "{{app_medusa_dir}}/tv"
    state: directory
    owner: "{{app_medusa_puid}}"
    group: "{{app_medusa_pgid}}"
    mode: 0755

- name: Ensure linuxserver/medusa image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/medusa
    source: pull
    force_source: yes
  register: pulled

- name: Remove medusa container
  community.docker.docker_container:
    name: medusa
    state: absent
  when: pulled.changed

- name: Get infos on medusa container
  community.docker.docker_container_info:
    name: medusa
  register: result

- name: Create medusa container
  ansible.builtin.shell: |
    docker run -d \
    --name=medusa \
    -e PUID={{app_medusa_puid}} \
    -e PGID={{app_medusa_pgid}} \
    -e TZ={{app_medusa_tz}} \
    -v /{{app_medusa_dir}}/config:/config:Z \
    -v /{{app_medusa_dir}}/downloads:/downloads:Z \
    -v /{{app_medusa_dir}}/tv:/tv:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/medusa
  when: 
    pulled.changed
    or
    result.exists == false
