---
- name: Install endlessh
  ansible.builtin.package:
    name: "endlessh"
    state: latest

- name: Forward port 22 to 2222
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    in_interface: ens3
    protocol: tcp
    match: tcp
    destination_port: '22'
    jump: REDIRECT
    to_ports: '2222'
    ip_version: ipv4
    comment: Redirect ssh traffic on ipv4 to port 2222

- name: Start endlessh service
  ansible.builtin.service:
    name: endlessh
    state: started
    enabled: yes
