---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_snipe_it_dir}}/config"
    state: directory
    owner: "{{app_snipe_it_puid}}"
    group: "{{app_snipe_it_pgid}}"
    mode: 0755

- name: Ensure linuxserver/snipe-it image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/snipe-it
    source: pull
    force_source: yes
  register: pulled

- name: Remove snipe-it container
  community.docker.docker_container:
    name: snipe-it
    state: absent
  when: pulled.changed

- name: Get infos on snipe-it container
  community.docker.docker_container_info:
    name: snipe-it
  register: result

- name: Create snipe-it container
  ansible.builtin.shell: |
    docker run -d \
    --name=snipe-it \
    -e NGINX_APP_URL={{app_snipe_it_nginx_app_url}} \
    -e APP_URL=https://{{app_snipe_it_nginx_app_url}} \
    -e APP_TIMEZONE={{app_snipe_it_app_timezone}} \
    -e APP_ENV={{app_snipe_it_app_env}} \
    -e APP_DEBUG={{app_snipe_it_app_debug}} \
    -e APP_LOCALE={{app_snipe_it_app_locale}} \
    -e MAIL_PORT_587_TCP_ADDR={{app_snipe_it_mail_port_587_tcp_addr}} \
    -e MAIL_PORT_587_TCP_PORT={{app_snipe_it_mail_port_587_tcp_port}} \
    -e MAIL_ENV_FROM_ADDR={{app_snipe_it_mail_env_from_addr}} \
    -e MAIL_ENV_FROM_NAME={{app_snipe_it_mail_env_from_name}} \
    -e MAIL_ENV_ENCRYPTION={{app_snipe_it_mail_env_encryption}} \
    -e MAIL_ENV_USERNAME={{app_snipe_it_mail_env_username}} \
    -e MAIL_ENV_PASSWORD={{app_snipe_it_mail_env_password}} \
    -e MYSQL_PORT_3306_TCP_ADDR={{app_snipe_it_mysql_port_3306_tcp_addr}} \
    -e MYSQL_PORT_3306_TCP_PORT={{app_snipe_it_mysql_port_3306_tcp_port}} \
    -e MYSQL_DATABASE={{app_snipe_it_mysql_database}} \
    -e MYSQL_USER={{app_snipe_it_mysql_user}} \
    -e MYSQL_PASSWORD={{app_snipe_it_mysql_password}} \
    -e PUID={{app_snipe_it_puid}} \
    -e PGID={{app_snipe_it_pgid}} \
    -v /{{app_snipe_it_dir}}/config:/config:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/snipe-it
  when: 
    pulled.changed
    or
    result.exists == false
