---
- name: Create directorys
  ansible.builtin.file:
    path: /opt/app-owncloud/data
    state: directory
    mode: 0755

- name: Ensure bitnami/owncloud image is pulled
  community.docker.docker_image:
    name: docker.io/bitnami/owncloud
    source: pull
    force_source: yes
  register: pulled

- name: Remove owncloud container
  community.docker.docker_container:
    name: owncloud
    state: absent
  when: pulled.changed

- name: Get infos on owncloud container
  community.docker.docker_container_info:
    name: owncloud
  register: result

- name: Create owncloud container
  ansible.builtin.shell: |
    docker run -d \
    --name=owncloud \
    -e OWNCLOUD_USERNAME={{app_owncloud_owncloud_username}} \
    -e OWNCLOUD_PASSWORD={{app_owncloud_owncloud_password}} \
    -e OWNCLOUD_EMAIL={{app_owncloud_owncloud_email}} \
    -e OWNCLOUD_SKIP_BOOTSTRAP={{app_owncloud_owncloud_skip_bootstrap}} \
    -e OWNCLOUD_HOST={{app_owncloud_owncloud_host}} \
    -e OWNCLOUD_DATABASE_TYPE={{app_owncloud_owncloud_database_type}} \
    -e OWNCLOUD_DATABASE_HOST={{app_owncloud_owncloud_database_host}} \
    -e OWNCLOUD_DATABASE_PORT_NUMBER={{app_owncloud_owncloud_database_port_number}} \
    -e OWNCLOUD_DATABASE_NAME={{app_owncloud_owncloud_database_name}} \
    -e OWNCLOUD_DATABASE_USER={{app_owncloud_owncloud_database_user}} \
    -e OWNCLOUD_DATABASE_PASSWORD={{app_owncloud_owncloud_database_password}} \
    -e ALLOW_EMPTY_PASSWORD={{app_owncloud_allow_empty_password}} \
    -e OWNCLOUD_SMTP_HOST={{app_owncloud_owncloud_smtp_host}} \
    -e OWNCLOUD_SMTP_PORT_NUMBER={{app_owncloud_owncloud_smtp_port_number}} \
    -e OWNCLOUD_SMTP_USER={{app_owncloud_owncloud_smtp_user}} \
    -e OWNCLOUD_SMTP_PASSWORD={{app_owncloud_owncloud_smtp_password}} \
    -e SUITECRM_SMTP_PROTOCOL={{app_owncloud_suitecrm_smtp_protocol}} \
    -e PHP_ENABLE_OPCACHE={{app_owncloud_php_enable_opcache}} \
    -e PHP_EXPOSE_PHP={{app_owncloud_php_expose_php}} \
    -e PHP_MAX_EXECUTION_TIME={{app_owncloud_php_max_execution_time}} \
    -e PHP_MAX_INPUT_TIME={{app_owncloud_php_max_input_time}} \
    -e PHP_MAX_INPUT_VARS={{app_owncloud_php_max_input_vars}} \
    -e PHP_MEMORY_LIMIT={{app_owncloud_php_memory_limit}} \
    -e PHP_POST_MAX_SIZE={{app_owncloud_php_post_max_size}} \
    -e PHP_UPLOAD_MAX_FILESIZE={{app_owncloud_php_upload_max_filesize}} \
    -v /opt/app-owncloud/data:/bitnami/owncloud:Z \
    --network=app-network \
    --restart unless-stopped \
    docker.io/bitnami/owncloud
  when: 
    pulled.changed
    or
    result.exists == false
