---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_nzbget_dir}}/config"
    state: directory
    owner: "{{app_nzbget_puid}}"
    group: "{{app_nzbget_pgid}}"
    mode: 0755

- name: Create downloads directory
  ansible.builtin.file:
    path: "{{app_nzbget_dir}}/downloads"
    state: directory
    owner: "{{app_nzbget_puid}}"
    group: "{{app_nzbget_pgid}}"
    mode: 0755

- name: Ensure linuxserver/nzbget image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/nzbget
    source: pull
    force_source: yes
  register: pulled

- name: Remove nzbget container
  community.docker.docker_container:
    name: nzbget
    state: absent
  when: pulled.changed

- name: Get infos on nzbget container
  community.docker.docker_container_info:
    name: nzbget
  register: result

- name: Create nzbget container
  ansible.builtin.shell: |
    docker run -d \
    --name=nzbget \
    -e PUID={{app_nzbget_puid}} \
    -e PGID={{app_nzbget_pgid}} \
    -e TZ={{app_nzbget_tz}} \
    -e NZBGET_USER={{app_nzbget_user}} \
    -e NZBGET_PASS={{app_nzbget_pass}} \
    -v /{{app_nzbget_dir}}/config:/config:Z \
    -v /{{app_nzbget_dir}}/downloads:/downloads:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/nzbget
  when: 
    pulled.changed
    or
    result.exists == false
