---
- name: Create data directory
  ansible.builtin.file:
    path: /opt/app-jenkins/data
    state: directory
    owner: '1001'
    group: '1001'
    mode: 0755

- name: Ensure bitnami/jenkins image is pulled
  community.docker.docker_image:
    name: docker.io/bitnami/jenkins
    source: pull
    force_source: yes
  register: pulled

- name: Remove jenkins container
  community.docker.docker_container:
    name: jenkins
    state: absent
  when: pulled.changed

- name: Get infos on jenkins container
  community.docker.docker_container_info:
    name: jenkins
  register: result

- name: Create jenkins container
  ansible.builtin.shell: |
    docker run -d \
    --name=jenkins \
    -e JENKINS_USERNAME={{app_jenkins_username}} \
    -e JENKINS_PASSWORD={{app_jenkins_password}} \
    -e JENKINS_EMAIL={{app_jenkins_email}} \
    -v /opt/app-jenkins/data:/bitnami/jenkins:Z \
    --network=app-network \
    --restart unless-stopped \
    docker.io/bitnami/jenkins
  when: 
    pulled.changed
    or
    result.exists == false
