---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_embystat_dir}}/config"
    state: directory
    owner: "{{app_embystat_puid}}"
    group: "{{app_embystat_pgid}}"
    mode: 0755

- name: Ensure linuxserver/embystat image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/embystat
    source: pull
    force_source: yes
  register: pulled

- name: Remove embystat container
  community.docker.docker_container:
    name: embystat
    state: absent
  when: pulled.changed

- name: Get infos on embystat container
  community.docker.docker_container_info:
    name: embystat
  register: result

- name: Create embystat container
  ansible.builtin.shell: |
    docker run -d \
    --name=embystat \
    -e PUID={{app_embystat_puid}} \
    -e PGID={{app_embystat_pgid}} \
    -e TZ={{app_embystat_tz}} \
    -v /{{app_embystat_dir}}/config:/config:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/embystat
  when: 
    pulled.changed
    or
    result.exists == false
