---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_lazylibrarian_dir}}/config"
    state: directory
    owner: "{{app_lazylibrarian_puid}}"
    group: "{{app_lazylibrarian_pgid}}"
    mode: 0755

- name: Create downloads directory
  ansible.builtin.file:
    path: "{{app_lazylibrarian_dir}}/downloads"
    state: directory
    owner: "{{app_lazylibrarian_puid}}"
    group: "{{app_lazylibrarian_pgid}}"
    mode: 0755

- name: Create books directory
  ansible.builtin.file:
    path: "{{app_lazylibrarian_dir}}/books"
    state: directory
    owner: "{{app_lazylibrarian_puid}}"
    group: "{{app_lazylibrarian_pgid}}"
    mode: 0755

- name: Ensure linuxserver/lazylibrarian image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/lazylibrarian
    source: pull
    force_source: yes
  register: pulled

- name: Remove lazylibrarian container
  community.docker.docker_container:
    name: lazylibrarian
    state: absent
  when: pulled.changed

- name: Get infos on lazylibrarian container
  community.docker.docker_container_info:
    name: lazylibrarian
  register: result

- name: Create lazylibrarian container
  ansible.builtin.shell: |
    docker run -d \
    --name=lazylibrarian \
    -e PUID={{app_lazylibrarian_puid}} \
    -e PGID={{app_lazylibrarian_pgid}} \
    -e TZ={{app_lazylibrarian_tz}} \
    -v /{{app_lazylibrarian_dir}}/config:/config:Z \
    -v /{{app_lazylibrarian_dir}}/downloads:/downloads:Z \
    -v /{{app_lazylibrarian_dir}}/books:/books:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/lazylibrarian
  when: 
    pulled.changed
    or
    result.exists == false
