---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_dillinger_dir}}/config"
    state: directory
    owner: "{{app_dillinger_puid}}"
    group: "{{app_dillinger_pgid}}"
    mode: 0755

- name: Ensure linuxserver/dillinger image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/dillinger
    source: pull
    force_source: yes
  register: pulled

- name: Remove dillinger container
  community.docker.docker_container:
    name: dillinger
    state: absent
  when: pulled.changed

- name: Get infos on dillinger container
  community.docker.docker_container_info:
    name: dillinger
  register: result

- name: Create dillinger container
  ansible.builtin.shell: |
    docker run -d \
    --name=dillinger \
    -e PUID={{app_dillinger_puid}} \
    -e PGID={{app_dillinger_pgid}} \
    -e TZ={{app_dillinger_tz}} \
    -v /{{app_dillinger_dir}}/config:/config:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/dillinger
  when: 
    pulled.changed
    or
    result.exists == false
