---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_ombi_dir}}/config"
    state: directory
    owner: "{{app_ombi_puid}}"
    group: "{{app_ombi_pgid}}"
    mode: 0755

- name: Ensure linuxserver/ombi image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/ombi
    source: pull
    force_source: yes
  register: pulled

- name: Remove ombi container
  community.docker.docker_container:
    name: ombi
    state: absent
  when: pulled.changed

- name: Get infos on ombi container
  community.docker.docker_container_info:
    name: ombi
  register: result

- name: Create ombi container
  ansible.builtin.shell: |
    docker run -d \
    --name=ombi \
    -e PUID={{app_ombi_puid}} \
    -e PGID={{app_ombi_pgid}} \
    -e TZ={{app_ombi_tz}} \
    -v /{{app_ombi_dir}}/config:/config:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/ombi
  when: 
    pulled.changed
    or
    result.exists == false
