---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_nzbhydra_dir}}/config"
    state: directory
    owner: "{{app_nzbhydra_puid}}"
    group: "{{app_nzbhydra_pgid}}"
    mode: 0755

- name: Create downloads directory
  ansible.builtin.file:
    path: "{{app_nzbget_dir}}/downloads"
    state: directory
    owner: "{{app_nzbget_puid}}"
    group: "{{app_nzbget_pgid}}"
    mode: 0755

- name: Ensure linuxserver/nzbhydra2 image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/nzbhydra2
    source: pull
    force_source: yes
  register: pulled

- name: Remove nzbhydra2 container
  community.docker.docker_container:
    name: nzbhydra2
    state: absent
  when: pulled.changed

- name: Get infos on nzbhydra2 container
  community.docker.docker_container_info:
    name: nzbhydra2
  register: result

- name: Create nzbhydra2 container
  ansible.builtin.shell: |
    docker run -d \
    --name=nzbhydra2 \
    -e PUID={{app_nzbhydra_puid}} \
    -e PGID={{app_nzbhydra_pgid}} \
    -e TZ={{app_nzbhydra_tz}} \
    -v /{{app_nzbhydra_dir}}/config:/config:Z \
    -v /{{app_nzbget_dir}}/downloads:/downloads:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/nzbhydra2
  when: 
    pulled.changed
    or
    result.exists == false
