---
- include_tasks: "{{ role_path }}/tasks/setup.yml"
  when: 
    docker_mariadb_enabled|bool
    or
    app_hedgedoc_enabled|bool
    or
    app_owncloud_enabled|bool
    or
    app_snipe_it_enabled|bool
