---
- include_tasks: "{{ role_path }}/tasks/setup.yml"
  when: 
    app_archisteamfarm_enabled|bool
    or
    app_bazarr_enabled|bool
    or
    app_beets_enabled|bool
    or
    app_boinc_enabled|bool
    or
    app_couchpotato_enabled|bool
    or
    app_dillinger_enabled|bool
    or
    app_dokuwiki_enabled|bool
    or
    app_embystat_enabled|bool
    or
    app_foldingathome_enabled|bool
    or
    app_freshrss_enabled|bool
    or
    app_grafan_enabled|bool
    or
    app_grocy_enabled|bool
    or
    app_hedgedoc_enabled|bool
    or
    app_heimdall_enabled|bool
    or
    app_jenkins_enabled|bool
    or
    app_loki_enabled|bool
    or
    app_nextcloud_enabled|bool
    or
    app_owncloud_enabled|bool
    or
    app_pihole_enabled|bool
    or
    app_prometheus_enabled|bool
    or
    app_sonarqube_enabled|bool
    or
    app_uptime_kuma_enabled|bool
