---
- include_tasks: "{{ role_path }}/tasks/setup.yml"
  when: 
    app_archisteamfarm_enabled|bool
    or
    app_bazarr_enabled|bool
    or
    app_beets_enabled|bool
    or
    app_boinc_enabled|bool
    or
    app_calibre_enabled|bool
    or
    app_couchpotato_enabled|bool
    or
    app_deluge_enabled|bool
    or
    app_dillinger_enabled|bool
    or
    app_dokuwiki_enabled|bool
    or
    app_duplicati_enabled|bool
    or
    app_emby_enabled|bool
    or
    app_embystat_enabled|bool
    or
    app_emulatorjs_enabled|bool
    or
    app_foldingathome_enabled|bool
    or
    app_freshrss_enabled|bool
    or
    app_grafan_enabled|bool
    or
    app_grocy_enabled|bool
    or
    app_headphones_enabled|bool
    or
    app_healthchecks_enabled|bool
    or
    app_hedgedoc_enabled|bool
    or
    app_heimdall_enabled|bool
    or
    app_homeassistant_enabled|bool
    or
    app_jellyfin_enabled|bool
    or
    app_jenkins_enabled|bool
    or
    app_keycloak_enabled|bool
    or
    app_lazylibrarian_enabled|bool
    or
    app_librespeed_enabled|bool
    or
    app_lidarr_enabled|bool
    or
    app_loki_enabled|bool
    or
    app_medusa_enabled|bool
    or
    app_mstream_enabled|bool
    or
    app_mylar_enabled|bool
    or
    app_netboot_enabled|bool
    or
    app_nextcloud_enabled|bool
    or
    app_nzbget_enabled|bool
    or
    app_nzbhydra_enabled|bool
    or
    app_ombi_enabled|bool
    or
    app_overseerr_enabled|bool
    or
    app_owncloud_enabled|bool
    or
    app_papermerge_enabled|bool
    or
    app_pihole_enabled|bool
    or
    app_piwigo_enabled|bool
    or
    app_plex_enabled|bool
    or
    app_prometheus_enabled|bool
    or
    app_pydio_enabled|bool
    or
    app_snipe_it_enabled|bool
    or
    app_sonarqube_enabled|bool
    or
    app_uptime_kuma_enabled|bool
