---
- name: Create app network
  community.docker.docker_network:
    name: app-network

- name: Create directory
  ansible.builtin.file:
    path: /opt/docker-swag/config/nginx/proxy-confs
    state: directory
    owner: "{{docker_swag_puid}}"
    group: "{{docker_swag_pgid}}"
    mode: 0755

- name: Copy files
  ansible.builtin.copy:
    src: "{{ item }}.subdomain.conf"
    dest: "/opt/docker-swag/config/nginx/proxy-confs/{{ item }}.subdomain.conf"
    owner: "{{docker_swag_puid}}"
    group: "{{docker_swag_pgid}}"
    force: "{{docker_swag_force}}"
    mode: 0644
  with_items:
    - "archisteamfarm"
    - "dokuwiki"
    - "duplicati"
    - "gitea"
    - "grafana"
    - "heimdall"
    - "homer"
    - "jenkins"
    - "keycloak"
    - "loki"
    - "nextcloud"
    - "phpmyadmin"
    - "pihole"
    - "plex"
    - "privatebin"
    - "prometheus"
    - "uptime-kuma"
  register: files

- name: Copy .htpasswd file
  ansible.builtin.copy:
    content: "{{ docker_swag_htpasswd }}"
    dest: /opt/docker-swag/config/nginx/.htpasswd
    owner: "{{docker_swag_puid}}"
    group: "{{docker_swag_pgid}}"
    force: "{{docker_swag_force}}"
    mode: 0644
  register: htpasswd_file

- name: Ensure linuxserver/swag image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/swag
    source: pull
    force_source: yes
  register: pulled

- name: Remove swag container
  community.docker.docker_container:
    name: swag
    state: absent
  when:
    files.changed
    or
    htpasswd_file.changed
    or
    pulled.changed

- name: Get infos on swag container
  community.docker.docker_container_info:
    name: swag
  register: result

- name: Create swag container
  ansible.builtin.shell: |
    docker run -d \
    --name=swag \
    --cap-add=NET_ADMIN \
    -e PUID={{docker_swag_puid}} \
    -e PGID={{docker_swag_pgid}} \
    -e TZ=Europe/Zurich \
    -e URL={{docker_swag_url}} \
    -e SUBDOMAINS=wildcard \
    -e VALIDATION=dns \
    -e DNSPLUGIN=cloudflare \
    -e ONLY_SUBDOMAINS=true \
    -v /opt/docker-swag/config:/config:Z \
    -p 443:443 \
    -p 80:80 \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/swag
  when:
    files.changed
    or
    htpasswd_file.changed
    or
    pulled.changed
    or
    result.exists == false

- name: Add swag container to bridge network
  ansible.builtin.shell:
    cmd: "docker network connect bridge swag"
  when:
    files.changed
    or
    htpasswd_file.changed
    or
    pulled.changed
    or
    result.exists == false
