---
- name: Create swag network
  community.docker.docker_network:
    name: swag-network

- name: Create directory
  ansible.builtin.file:
    path: /opt/docker-swag/config/nginx/proxy-confs
    state: directory
    owner: '16704'
    group: '16704'
    mode: 0755

- name: Copy files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/docker-swag/config/nginx/proxy-confs/{{ item }}"
    owner: '16704'
    group: '16704'
    mode: 0644
  with_items:
    - "archisteamfarm.subdomain.conf"
    - "grafana.subdomain.conf"
    - "heimdall.subdomain.conf"
    - "jenkins.subdomain.conf"
    - "loki.subdomain.conf"
    - "nextcloud.subdomain.conf"
    - "prometheus.subdomain.conf"
    - "uptime-kuma.subdomain.conf"

- name: Copy .htpasswd file
  ansible.builtin.copy:
    content: "{{ docker_swag_htpasswd }}"
    dest: /opt/docker-swag/config/nginx/.htpasswd
    owner: '16704'
    group: '16704'
    mode: 0644

- name: Ensure linuxserver/swag image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/swag
    source: pull
    force_source: yes
  register: pulled

- name: Remove swag container
  community.docker.docker_container:
    name: swag
    state: absent
  when: pulled.changed

- name: Get infos on swag container
  community.docker.docker_container_info:
    name: swag
  register: result

- name: Create swag container
  ansible.builtin.shell: |
    docker run -d \
    --name=swag \
    --cap-add=NET_ADMIN \
    -e PUID=16704 \
    -e PGID=16704 \
    -e TZ=Europe/Zurich \
    -e URL=app.crazycraftland.info \
    -e SUBDOMAINS=wildcard \
    -e VALIDATION=dns \
    -e DNSPLUGIN=cloudflare \
    -e ONLY_SUBDOMAINS=true \
    -v /opt/docker-swag/config:/config:Z \
    -p 443:443 \
    -p 80:80 \
    --network=swag-network \
    --restart unless-stopped \
    lscr.io/linuxserver/swag
  when:
    pulled.changed
    or
    result.exists == false

- name: Add swag container to bridge network
  ansible.builtin.shell:
    cmd: "docker network connect bridge swag"
  when:
    pulled.changed
    or
    result.exists == false