---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_beets_dir}}/config"
    state: directory
    owner: "{{app_beets_puid}}"
    group: "{{app_beets_pgid}}"
    mode: 0755

- name: Create music directory
  ansible.builtin.file:
    path: "{{app_beets_dir}}/music"
    state: directory
    owner: "{{app_beets_puid}}"
    group: "{{app_beets_pgid}}"
    mode: 0755

- name: Create downloads directory
  ansible.builtin.file:
    path: "{{app_beets_dir}}/downloads"
    state: directory
    owner: "{{app_beets_puid}}"
    group: "{{app_beets_pgid}}"
    mode: 0755

- name: Ensure linuxserver/beets image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/beets
    source: pull
    force_source: yes
  register: pulled

- name: Remove beets container
  community.docker.docker_container:
    name: beets
    state: absent
  when: pulled.changed

- name: Get infos on beets container
  community.docker.docker_container_info:
    name: beets
  register: result

- name: Create beets container
  ansible.builtin.shell: |
    docker run -d \
    --name=beets \
    -e PUID={{app_beets_puid}} \
    -e PGID={{app_beets_pgid}} \
    -e TZ={{app_beets_tz}} \
    -v /{{app_beets_dir}}/config:/config:Z \
    -v /{{app_beets_dir}}/music:/music:Z \
    -v /{{app_beets_dir}}/downloads:/downloads:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/beets
  when: 
    pulled.changed
    or
    result.exists == false
