---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_boinc_dir}}/config"
    state: directory
    owner: "{{app_boinc_puid}}"
    group: "{{app_boinc_pgid}}"
    mode: 0755

- name: Ensure linuxserver/boinc image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/boinc
    source: pull
    force_source: yes
  register: pulled

- name: Remove boinc container
  community.docker.docker_container:
    name: boinc
    state: absent
  when: pulled.changed

- name: Get infos on boinc container
  community.docker.docker_container_info:
    name: boinc
  register: result

- name: Create boinc container
  ansible.builtin.shell: |
    docker run -d \
    --name=boinc \
    -e PUID={{app_boinc_puid}} \
    -e PGID={{app_boinc_pgid}} \
    -e TZ={{app_boinc_tz}} \
    -v /{{app_boinc_dir}}/config:/config:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/boinc
  when: 
    pulled.changed
    or
    result.exists == false
