---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_jellyfin_dir}}/config"
    state: directory
    owner: "{{app_jellyfin_puid}}"
    group: "{{app_jellyfin_pgid}}"
    mode: 0755

- name: Create tvshows directory
  ansible.builtin.file:
    path: "{{app_jellyfin_dir}}/tvshows"
    state: directory
    owner: "{{app_jellyfin_puid}}"
    group: "{{app_jellyfin_pgid}}"
    mode: 0755

- name: Create movies directory
  ansible.builtin.file:
    path: "{{app_jellyfin_dir}}/movies"
    state: directory
    owner: "{{app_jellyfin_puid}}"
    group: "{{app_jellyfin_pgid}}"
    mode: 0755

- name: Ensure linuxserver/jellyfin image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/jellyfin
    source: pull
    force_source: yes
  register: pulled

- name: Remove jellyfin container
  community.docker.docker_container:
    name: jellyfin
    state: absent
  when: pulled.changed

- name: Get infos on jellyfin container
  community.docker.docker_container_info:
    name: jellyfin
  register: result

- name: Create jellyfin container
  ansible.builtin.shell: |
    docker run -d \
    --name=jellyfin \
    -e PUID={{app_jellyfin_puid}} \
    -e PGID={{app_jellyfin_pgid}} \
    -e TZ={{app_jellyfin_tz}} \
    -v /{{app_jellyfin_dir}}/config:/config:Z \
    -v /{{app_jellyfin_dir}}/tvshows:/data/tvshows:Z \
    -v /{{app_jellyfin_dir}}/movies:/data/movies:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/jellyfin
  when: 
    pulled.changed
    or
    result.exists == false
