---
- name: Create directory
  ansible.builtin.file:
    path: /opt/app-prometheus/config
    state: directory
    owner: nobody
    group: nobody
    mode: 0755

- name: Copy prometheus file
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /opt/app-prometheus/config/prometheus.yml
    owner: nobody
    group: nobody
    mode: 0644

- name: Ensure prom/prometheus image is pulled
  community.docker.docker_image:
    name: docker.io/prom/prometheus
    source: pull
    force_source: yes

- name: Remove prometheus container
  community.docker.docker_container:
    name: prometheus
    state: absent
  when: pulled.changed

- name: Create prometheus-data volume
  community.docker.docker_volume:
    name: prometheus-data

- name: Get infos on prometheus container
  community.docker.docker_container_info:
    name: prometheus
  register: result

- name: Create prometheus container
  ansible.builtin.shell: |
    docker run -d \
    --name=prometheus \
    -v /opt/app-prometheus/config:/etc/prometheus:Z \
    -v prometheus-data:/prometheus:Z \
    --network=swag-network \
    --restart unless-stopped \
    docker.io/prom/prometheus
  when:
    pulled.changed
    or
    result.exists == false
