---
- name: Create config directory
  ansible.builtin.file:
    path: /opt/app-endlessh/config
    state: directory
    owner: "{{app_endlessh_puid}}"
    group: "{{app_endlessh_pgid}}"
    mode: 0755

- name: Ensure linuxserver/endlessh image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/endlessh
    source: pull
    force_source: yes
  register: pulled

- name: Remove endlessh container
  community.docker.docker_container:
    name: endlessh
    state: absent
  when: pulled.changed

- name: Get infos on endlessh container
  community.docker.docker_container_info:
    name: endlessh
  register: result

- name: Create endlessh container
  ansible.builtin.shell: |
    docker run -d \
    --name=endlessh \
    -e PUID={{app_endlessh_puid}} \
    -e PGID={{app_endlessh_pgid}} \
    -e TZ={{app_endlessh_tz}} \
    -e MSDELAY={{app_endlessh_msdelay}} \
    -e MAXLINES={{app_endlessh_maxlines}} \
    -e MAXCLIENTS={{app_endlessh_maxclients}} \
    -e LOGFILE={{app_endlessh_logfile}} \
    -e BINDFAMILY={{app_endlessh_bindfamily}} \
    -v /opt/app-endlessh/config:/config:Z \
    -p 2222:2222 \
    --restart unless-stopped \
    lscr.io/linuxserver/endlessh
  when: 
    pulled.changed
    or
    result.exists == false

- name: Add endlessh container to bridge network
  ansible.builtin.shell:
    cmd: "docker network connect bridge endlessh"
  when: 
    pulled.changed
    or
    result.exists == false
