---
app_healthchecks_enabled: false
app_healthchecks_puid: '16704'
app_healthchecks_pgid: '16704'
app_healthchecks_dir: "/opt/app-healthchecks"
app_healthchecks_site_name: ""
app_healthchecks_default_from_email: ""
app_healthchecks_email_host: ""
app_healthchecks_email_port: ""
app_healthchecks_email_host_user: ""
app_healthchecks_email_host_password: ""
app_healthchecks_email_use_tls: false
app_healthchecks_allowed_hosts: ["*"]
app_healthchecks_superuser_email: ""
app_healthchecks_superuser_password: ""
app_healthchecks_regenerate_settings: false
app_healthchecks_site_logo_url: ""
app_healthchecks_secret_key: ""
app_healthchecks_apprise_enabled: false
