---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_freshrss_dir}}/config"
    state: directory
    owner: "{{app_freshrss_puid}}"
    group: "{{app_freshrss_pgid}}"
    mode: 0755

- name: Ensure linuxserver/freshrss image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/freshrss
    source: pull
    force_source: yes
  register: pulled

- name: Remove freshrss container
  community.docker.docker_container:
    name: freshrss
    state: absent
  when: pulled.changed

- name: Get infos on freshrss container
  community.docker.docker_container_info:
    name: freshrss
  register: result

- name: Create freshrss container
  ansible.builtin.shell: |
    docker run -d \
    --name=freshrss \
    -e PUID={{app_freshrss_puid}} \
    -e PGID={{app_freshrss_pgid}} \
    -e TZ={{app_freshrss_tz}} \
    -v /{{app_freshrss_dir}}/config:/config:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/freshrss
  when: 
    pulled.changed
    or
    result.exists == false
