---
- name: Ensure grafana/grafana-enterprise image is pulled
  community.docker.docker_image:
    name: docker.io/grafana/grafana-enterprise
    source: pull
    force_source: yes
  register: pulled

- name: Remove grafana container
  community.docker.docker_container:
    name: grafana
    state: absent
  when: pulled.changed

- name: Create grafana-config volume
  community.docker.docker_volume:
    name: grafana-config

- name: Create grafana-data volume
  community.docker.docker_volume:
    name: grafana-data

- name: Get infos on grafana container
  community.docker.docker_container_info:
    name: grafana
  register: result

- name: Create grafana container
  ansible.builtin.shell: |
    docker run -d \
    --name=grafana \
    -v grafana-data:/var/lib/grafana:Z \
    -v grafana-config:/etc/grafana:Z \
    --network=app-network \
    --restart unless-stopped \
    docker.io/grafana/grafana-enterprise
  when:
    pulled.changed
    or
    result.exists == false
