---
app_endlessh_enabled: false
app_endlessh_puid: '16704'
app_endlessh_pgid: '16704'
app_endlessh_tz: "Europe/Zurich"
app_endlessh_msdelay: '10000'
app_endlessh_maxlines: '32'
app_endlessh_maxclients: '4096'
app_endlessh_logfile: false
app_endlessh_bindfamily: ''